### ISSUE TITLE
Where can i submit the addon language translations?

### ISSUE THREAD

**Issue by runningcheese** [ettoolong/PopupWindow#1]
love this addon so much, hope will be better, Where can i submit the addon language translations?

**Comment by ettoolong** [comment]
You can creating a pull request or download [this file](https://github.com/ettoolong/PopupWindow/blob/master/_locales/en/messages.json) and translate it ( see language tags [here](https://developer.chrome.com/webstore/i18n?csw=1#localeTable) ).

thank you.
