### ISSUE TITLE
ability to send web page to desktop shortcut as windowed?

### ISSUE THREAD

**Issue by k1nghat** [ettoolong/PopupWindow#13]
in chrome i take many websites and create a shortcut to desktop and enable the option to open as window. this way these webpages look more like apps. is this possible with your extension or at all in firefox? i even have these websites auto open/run when i login to my desktop(linux/win).

**Comment by ettoolong** [comment]
I think this issue is similar with #12 and #7
Does that meet your requirements?

**Comment by k1nghat** [comment]
yep those look like what I'm after.
