### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by grahamperrin** [ettoolong/PopupWindow#15]
Distinct from #12

I'd like a tab to pop up in response to a keyboard shortcut. 

Related, from <https://addons.mozilla.org/addon/popup-window/reviews/1118399/>:

> 1.) Add a keyboard shortcut

**Comment by ettoolong** [comment]
Support keyboard shortcut in version 0.0.8 (Only for Firefox 66+)

**Comment by grahamperrin** [comment]
Thanks!
