### ISSUE TITLE
Mouse Y-offset is "off"

### ISSUE THREAD

**Issue by MadMartian** [ettoolong/PopupWindow#17]
When opening a window in web-app mode or using the pop-up feature the actual mouse y-position is many pixels (about 50-100) below what the web-page registers.  It's as if the web browser thinks the tabs, menu and toolbars are still visible and part of the top layout even though the window renders correctly (without them).

**Popup window**: 0.0.8
**Firefox**: 67.0.1 (64-bit Linux)

_Example image_
![image](https://user-images.githubusercontent.com/2112359/59372432-5a87b080-8cfc-11e9-9c38-cae2d2573140.png)

**Comment by latk** [comment]
I can reproduce this problem. It only occurs with fresh popup windows. If the window is closed and then restored (e.g. Ctrl-Shift-N) then everything works as expected. So that is a workaround if reloading the tab is OK.

However, this kind of issue is likely to be an upstream problem in Firefox: clearly, the rendering engine or something is getting confused about its coordinate system. I don't think this can be fixed via an addon.

**Comment by arthurmv** [comment]
> 
> 
> When opening a window in web-app mode or using the pop-up feature the actual mouse y-position is many pixels (about 50-100) below what the web-page registers. It's as if the web browser thinks the tabs, menu and toolbars are still visible and part of the top layout even though the window renders correctly (without them).
> 
> **Popup window**: 0.0.8
> **Firefox**: 67.0.1 (64-bit Linux)
> 
> _Example image_
> ![image](https://user-images.githubusercontent.com/2112359/59372432-5a87b080-8cfc-11e9-9c38-cae2d2573140.png)

The same thing happens to me...

**Comment by nenad** [comment]
@latk and @MadMartian, do you use X or Wayland? I experience the same, and I'm on Wayland myself.

It's interesting that it also happens on Windows, which should point in this being Firefox problem.

**Comment by latk** [comment]
I am using X. Everything here points to an upstream problem. This add-on itself is working as expected.

**Comment by FumbarHuygens** [comment]
I am also getting this issue on Firefox Quantum 68.0.1 64bit, Windows 10 Pro.

**Comment by nenad** [comment]
I reported this as a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1563831

**Comment by HellfireXD** [comment]
There is another FireFox addon that does not experience this issue although not on Github.  Makes me wonder if there is another way to do this?

https://addons.mozilla.org/en-US/firefox/addon/new-window-without-toolbar/

**Comment by HellfireXD** [comment]
So i did a little experiment and i noticed something interesting.  
If i have a sidebar open on the right side of my browser, it offsets the mouse to the left and vice versa.
This got me thinking so I did another test and found something corresponding to the y offset. 
If i enable the menu and the bookmarks bars, the y offset is increased, if i disable the menu and the bookmarks bars, the y offset is decreased. 

It may be possible to correct this by pulling the height of the bars and offsetting the y axis by that amount.

**Comment by fc757** [comment]
My man. Thank you for pointing out the new-window-without-toolbar extension. I love using some webpages in more compact tight windows. Chrome got me hooked on App Mode but we hateses Chrome. Found the savior extensions that do the same thing in Firefox but they got all busted.

Trials and tribulations. Good work on the troubleshooting there. Hopefully someone figures it out soon and it will work again. But... for... how... long.

**Comment by ettoolong** [comment]
@HellfireXD thanks, there are some different between PopupWindow and new-window-without-toolbar:

- **new-window-without-toolbar** open an new window with current tab's URL
- **PopupWindow** MOVE current tab to new window

In other words, if you are playing a web game or watching a video, **PopupWindow** move current tab to new window, and keep all browsing status(game and video progress, etc.)

If you don't need keep browsing status, you can use **new-window-without-toolbar**, it open a new window with the same URL(imagine you refresh the tab by F5 hotkey)

With **PopupWindow**, if you use context menu(right click on an link) to **open the link in pop-up window** that can prevent from the Y-offset issue (the real behavior is open a new window with link URL, it's the same with **new-window-without-toolbar**)

Anyway, it's still a Firefox bug that needs to be fixed.

thanks for all your feedback.

**Comment by ettoolong** [comment]
> I reported this as a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1563831
> 
> The author can close the issue.

https://bugzilla.mozilla.org/show_bug.cgi?id=1565525
@MadMartian, @latk and @FumbarHuygens, Can you test this issue on Firefox 70?

**Comment by FumbarHuygens** [comment]
>@FumbarHuygens, Can you test this issue on Firefox 70?

@ettoolong 

I tried it on on the beta channel and it still occurred.

**Comment by ettoolong** [comment]
Firefox 70 fix this bug.
Today I tested this issue on Firefox 70 (stable release) on Win10 & Ubuntu Desktop 18.04, no more the shift problem.
