### ISSUE TITLE
Can't Maximize Pop up Window

### ISSUE THREAD

**Issue by benyaminl** [ettoolong/PopupWindow#24]
Hello, I've silly problem on Windows, I can't maximize the Window. Is there anyway to make the window could have maximize or minimized? Thanks

**Comment by dawaltconley** [comment]
I wonder if this is related to #23: I also cannot minimize or maximize using Firefox in GNOME (Pop!_OS 20.10), and the pop-up is always on top.

**Comment by benyaminl** [comment]
Ehm it's on windows sir, it isn't on linux

**Comment by Fuseteam** [comment]
this seems like a duplicate of #6

**Comment by benyaminl** [comment]
Close duplicated of #6
