### ISSUE TITLE
[Feature Request] Webpage Conditional List

### ISSUE THREAD

**Issue by maverick74** [ettoolong/PopupWindow#7]
Would be good to be able to create a Conditional Webpage list where all websites on that list would be automatically sent to their popup window.

This has a specially interest for business users. With this feature one can use the set webpages that are SaaS systems to open in their window automatically.

This would also allow for users to create desktop icons that will specifically open a pre-determined webpage for a SaaS in a popup window (even if it first has to load a regular Firefox session and then closeit while it pops-it-out)

**Comment by indeedwatson** [comment]
I really want this feature as well.

**Comment by Fuseteam** [comment]
something tells me this is what https://github.com/ettoolong/WebAppMode does

**Comment by maverick74** [comment]
> something tells me this is what https://github.com/ettoolong/WebAppMode does

Well, the [PopUp](https://addons.mozilla.org/pt-PT/firefox/addon/popup/) addon also does that, in kind of an All-In-one Addon.

However, thanks to Windows 10 "limitations" we can't have a maximized popup windows by default (you have to set its dimensions manually)

**Comment by Fuseteam** [comment]
> > something tells me this is what https://github.com/ettoolong/WebAppMode does
> 
> Well, the [PopUp](https://addons.mozilla.org/pt-PT/firefox/addon/popup/) addon also does that, in kind of an All-In-one Addon.
> 
> However, thanks to Windows 10 "limitations" we can't have a maximized popup windows by default (you have to set its dimensions manually)

appearently the addon doesn't allow to start maximized on linux either tho i'm not sure if there's a liimitation for that on linux's end

**Comment by maverick74** [comment]
> appearently the addon doesn't allow to start maximized on linux either tho i'm not sure if there's a liimitation for that on linux's end

No. The only way was to set the desired webpages has homepages and when the browser runs it pops up the desired pages closing them on the main browser window

(too confusing?!)

**Comment by Fuseteam** [comment]
so clicking the popup button won't start the pop up window in maximized state? it seems to ignore my tiling wm's rules so far :thinking:

**Comment by maverick74** [comment]
From my experience, (not recently!):
popups maximized were allowed on Linux (tested on SUSE+Plasma)
In windows they were not allowed in the sense there was always a margin of (if I recall correctly) around 10px around the window frame.

What DE are you using? 
I always tested it under kwin on KDE plasma. (not sure if I tried on openbox thru Lxqt)

**Comment by Fuseteam** [comment]
i'm using the dwm window manager, most of the windows open according to my tiling rules but these popup window seem to override it somehow

**Comment by maverick74** [comment]
It might have something to do with dwm then.

Have you tried it under kwin? (it's not as heavy has most people say... in fact, lately, it very been so lite that the lxqt folks are even considering using it)

**Comment by Fuseteam** [comment]
i haven't no, i mainly use dwm for it hackability, tiling and tagging features. tho i kinda doubt it's a dwm issue, considering every other window works just fine

**Comment by maverick74** [comment]
if it's not the wm, then i'm out of clues :)

**Comment by GitMensch** [comment]
Together with the documentation in the repo, which would be "fixed" by #30 I suggest to add a notice to the [addons.mozilla page for this extension](https://addons.mozilla.org/de/firefox/addon/popup-window/) pointing to the WAM extension there, too.
