### ISSUE TITLE
视频窗口弹出就无法还原了

### ISSUE THREAD

**Issue by Jerry-1984** [ettoolong/PopupWindow#9]
配合Maximize Video扩展将视频弹出成独立窗口后就无法还原回主窗口了！

**Comment by jiayiming** [comment]
Maximize Video应该加一个还原按钮或者快捷键

**Comment by ettoolong** [comment]
Update: [Keyboard Shortcut](https://github.com/ettoolong/MaximizeVideo/issues/8
)
